name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Se déclenche uniquement sur la branche main
    paths:
      - "projects/*/**"  # Détecte les changements dans n'importe quel sous-dossier de 'projects'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.changed_files.outputs.changed_folders) }}

    needs: changed_files

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./projects/${{ matrix.folder }}
        file: ./projects/${{ matrix.folder }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.folder }}:latest

    - name: Logout from Docker
      run: docker logout ghcr.io

  changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.filter.outputs.changed_folders }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Detect changed folders
      id: filter
      run: |
        echo "Running folder detection"
        folders=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^projects/' | cut -d'/' -f2 | sort | uniq)
        echo "Changed folders: $folders"
        echo "::set-output name=changed_folders::[$(echo $folders | jq -R -s -c 'split("\n")[:-1]')]"